version: '3'
services:
  consul:
    image: consul
    ports:
      - 8500:8500
      - 8600:8600

  web:
    build:
      context: ./docker/web
    volumes:
      - ./public:/usr/local/apache2/htdocs
    ports:
      - 8000:80
    depends_on:
      - fpm
      - consul
    command: ["/bin/envconsul", "-consul-addr", "consul:8500", "-prefix", "httpd", "httpd-foreground"]

  fpm:
    build:
      context: ./docker/fpm
    volumes:
      - .:/var/www/html
    depends_on:
      - consul
    entrypoint: ["/bin/envconsul", "-consul-addr", "consul:8500", "-prefix", "php", "/usr/local/bin/docker-php-entrypoint"]
    command: ["php-fpm"]
